---
- shell: echo '1' > /proc/sys/net/ipv4/ip_forward

- name: Join node to Kubernetes control plane.
  shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']
